/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp0;

import  tp0.Ex1.V1.MainV1;
import  tp0.Ex1.V2.MainV2;
import tp0.Ex1.V3.MainV3;

public class App {
    
    public static void main(String[] args) throws Exception{
        MainV1.exemple();
        System.out.println("\n");
        MainV2.exemple();
        System.out.println("\n");
        MainV3.exemple();
        System.out.println("\n");
    }
}
