/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp0;

import tp0.V1.MainV1;

public class App {
    
    public static void main(String[] args) {
        MainV1.exemple();
    }
}
