/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp0;

import org.junit.Test;

import tp0.Ex1.V5.*;

import static org.junit.Assert.*;

public class AppTest {
/*
    @Test
    public void renduMonnaieOk(){
        Caisse caisse = new Caisse();
        Commande commande0 = new Commande(new Serveur(1234,"toto"), new Client(1),4658);  
        Article repas = new Article("platChaud",0);
        try{
            commande0.ajoutArticle(repas);
            commande0.recap();
            caisse.ajoutCommande( commande0);
        }
        catch(Exception e){}
        System.out.println("a rendre " + (15.75 - commande0.addition()));
        assertTrue(caisse.peutRendreLaMonnaie(15.75 - commande0.addition()));
        
    }*/

    /*public void renduMonnaiePasOk(){
        Caisse caisse = new Caisse();
        Commande commande0 = new Commande(new Serveur(1234,"toto"), new Client(1),4658);  
        Article repas = new Article("platChaud",0);
        try{
            commande0.ajoutArticle(repas);
            commande0.recap();
            caisse.ajoutCommande( commande0);
        }
        catch(Exception e){}
        System.out.println("a rendre " + (27 - commande0.addition()));
        assertFalse(caisse.peutRendreLaMonnaie((27 - commande0.addition())));
        
    }*/
  
}
